source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'PQCheckSDK_Example' do
  pod 'PQCheckSDK', :path => '../'
  pod 'MBProgressHUD'
end

target 'PQCheckSDK_Tests' do
  pod 'PQCheckSDK', :path => '../'

  pod 'Specta'
  pod 'Expecta'
end
