# references:
# * http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7.2
cache: cocoapods
podfile: Example/Podfile

before_install:
  - gem install activesupport
  - gem install cocoapods -v 0.38.0 # Since Travis is not always on latest version
  - pod install --project-directory=Example

branches:
  only:
    - develop

env:
  global:
    - secure: "EcHl/7lkY5kcxcxyC6B4E1LzAgTCR268QgPtytkEp/e2c7VNThB41iwL4Fp/MQy0feFy1MP43+xDTxNHyxCtHFgnE8pBueOIwZpahBB7aSxaxejZkSopwuIrHmMy1JfKLEo2rLTi5RPaDWEZJZrCSag73fedATeIDMbasV9RPrA/aznv6uwwih22tZVogx/zaGbKrr3pLHs8monfC1lhyLphYD6ujZWBAjeycDiUPzDcJSYMHfJ5ZD7JtUlMQONnOTZc63u4dLdcWmcPmIcCK6jPhSiIhqkPq1eRWRSWZ+eSdPEM7LZM1qb5urWSCLJG5KxI0RUHc+3a1zXLr7X8peBbUkVGMpk/NV/yteqWJHFsPWEmyKl0AM1aGVzTd0x2uudZzCh5j2RGKwjGiKAZ+4ppUPeeDeNEPDulPooOtLn1KXKJSd2SMIAiokErc2O25vUwY9rDtMP+4hcUyqPqi7WrQTjqdX5Gjd7JGZu1yt7G1MrSPjD5mFL/b/q0SXkdkKsW+v1yoqVRLjj6LGwvKI6PHn3mLkXDZ5TQc9uOiNfmXaeyKHXT4gHU4AS1PI+M5HZM7uy+52T2Poub4f2ggg6hOblGEC9cE+atnSCpZ0zOkZhD6bNe4IsDNv0WYkktI+32qZP8eV7M/dAGwMQvb4Lg76sGF0k/jJIeZ09Daq0="
    - secure: "gn7B1pV3am+FOBL4h6g0jbrBJZRdEMzIm/xj1agqY6HGeWoAczns4sLuccSaI5oGKX4C8YtuWYUAuogm17hZgjbiDt0SBaFwJvFB/puqIMLGpwpAmavtHcqLHGzQHUmP5Nnm61hvykiRCV6/5/nTQAWPbKBBvNOGDHzYN9bteIIb9oa0bOcF12/AEsJXY/XWdpjbYywA5GQtxMHTz6WRUcKV31PlvSMwK98VTWstiRStRGfU8vD4HxLo/ri51JqLmLUR6TvGMrRs4aU2sAQBXFn+yb+MH6wlR8S5upmUXagpcg8R4Hf+JQXznYGtqpgm5AtlA87JuhUTLHSZ8dGPVlGIgISa4kj2DucaygKw/rz2HRDzeTu6xFMsZjEZuXor7UzXimFNTMS4aehsN2gYdPvSRPStFSV/mAI82b4FChSY/Kjma7vUXGWMUHhEtDskNyYjAipdig5INrtq9Ts9IAOY6hJzCHx8GFoRxpzrlyU498MJa05x/DFQor+pREUMjSsUsnhXLn/EyqCxHMfbAzgXNOTZjdRiePkwf4TczqRXTtWq0Q+tAh7n5K2em6VBjOmqzc+JTIwpYPlQlnKrtpWfSZ/0tCVNP9vyj/PumYPpMHcPtc/3CTGbmUEMo82J3BHOlJridKzIGowuIZSK+EVIFOIF6ySUNW7szQFQyB0="
    - secure: "ooQfrcYQ7DNSioB3Ex7x3DIDo1qXepVyGSsSOU7HgB7VPpMCUUF4gaCnZfEjBs0Glv9PZcMTDehdXgbdCleHi1ruh3qfrolLwznscR85x03c+o/z8DB3gDMDuZHENhmmtqOAhldKFPgtWxfrapSC39CcHmwEdBvm43FrJp06CODx02PqK+9hlqMdB5fc6pcsQ2WMIlZuml74mfEMLMCgzrURCNDPApkEiZ2nLY8qFDw0ffpcNRlpPeCNaDGJ7uIk57UiPZ2m4ny5yZ2FR3jdvSfBYV0CnSaBxDeaFJG3QK+t8a8ZdWS+Ir3vF4hWByvaf9Wh5PeG2yqJjuSEqeFdexqpTTUIhy1ms4tCyhCn/WHcwHTVMeiudPDvLoztvFb70WCy7zp8lglRVxU5iPFHFN5OSae/edel7frQ3VJQCbItfyzkt4xCrA3RHGZ++RIb6db5YYTLWjiaiPdm6Wceor/83M8eUlR1741bC1DpfyfhoLNU+nLqiRS2GI2WgUhxaFhi363AKD3DIL8F/5ah50qMkbjosR+fOLe2cY1hBt0o7rlnB+sfa4K1kDsCZ76zkBJaJmxmSsBBjnQB96nuVFROdrqbZGRxbrjEnqSYFCEx8z0132IkUmtvQq2xHgkdsaRo2oVf0zc1XEqeocHniKQ5MdT8xPIQAgoP7JktdU0="

script:
  - pod lib lint --allow-warnings
  - xctool -workspace Example/PQCheckSDK.xcworkspace -scheme PQCheckSDK -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace Example/PQCheckSDK.xcworkspace -scheme PQCheckThinSDK_Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -workspace Example/PQCheckSDK.xcworkspace -scheme Documentation
