# references:
# * http://www.objc.io/issue-6/travis-ci.html

language: objective-c
cache: cocoapods
podfile: Example/Podfile

before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example

branches:
  only:
    - thin.sdk

script:
  - pod lib lint --allow-warnings
  - xctool -workspace Example/PQCheckSDK.xcworkspace -scheme PQCheckSDK -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace Example/PQCheckSDK.xcworkspace -scheme PQCheckThinSDK_Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -workspace Example/PQCheckSDK.xcworkspace -scheme Documentation
