# references:
# * http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7.2
# cache: cocoapods
podfile: Example/Podfile

before_install:
  - gem uninstall cocoapods
  - gem install activesupport
  - gem install bundler
  - gem install cocoapods -v 0.38.0 # RestKit only works with this version of CocoaPods
  - brew install appledoc
  - pod install --project-directory=Example

branches:
  only:
    - develop

script:
  - pod lib lint --allow-warnings --verbose
  - xctool -workspace Example/PQCheckSDK.xcworkspace -scheme PQCheckSDK -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace Example/PQCheckSDK.xcworkspace -scheme PQCheckThinSDK_Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -workspace Example/PQCheckSDK.xcworkspace -scheme Documentation
