# references:
# * http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7.2
# cache: cocoapods
podfile: Example/Podfile

before_install:
  - gem uninstall cocoapods
  - gem install activesupport
  - gem install bundler
  - gem install cocoapods -v 0.38.0 # RestKit only works with this version of CocoaPods
  - curl -sL https://gist.github.com/henrikhodne/7ac6d02ff9a24a94720c/raw/install_appledoc.sh | sh
  - pod install --project-directory=Example

branches:
  only:
    - develop

env:
  global:
    - secure: "cDDnkBLqd6AWl1JJF6LK1edDmWxu6D1N8nuk+yYzIFs4HdkYBq+dK/c1nWUdKmCMiGBzKGDWHHsglZ0JW66tx1KlEySwwr3okvmGtfny4M1o5SeVEz3NMfaim09tYwpq76MQpMPxYchBvpoklt3pEDMaQO3TJe5hrLEWjcKvVeUc/7KXnhDdwKRQGbH6aqYj80M142MxPjj+pvXq8Wr+g2FEkbG3XOaeuN26N7hz+ZMRBpIo/R5tut/m2gUpqB/XQNplaX7AOCj9FtNeZe4cNiqnCaq7QSSZWOjraLoF5ChtjOFeSRHju2ktB2G9hmu85wXlssiuAk7IGW8/4DvhiouJ1TiI82uCK7y/A9HAceRwi897fJA3uGwnZua2iypmzqAX5Qy8DUIlceWM2nTtG6qKCD5FoP6Twn7GG7Tt4yiTnoifH0m3LhU4PRSZevt4bhr5JJar5hZcot3Q7xAwTWiDrX45p4i3cmLa3jphgGL1vSqQJ3yU3/XXbSkweZNzY8DUmJYF68o42qQvb1Pf5UmyHPAQUmfY6KYJlBP0WfRdkZUEcfS/N/VW1EBHJqF4fATmf2az5p3u59v+Ffcn3TpfpHLUgUOMTcd844INZ6xSrXwJzdfMSiqvQNaJyHv5ZqwudpwO9Bp9Nh6GgvEOaJVAyRFy4gdcSJo15BbMr/s="

script:
  - pod lib lint --allow-warnings
  - xctool -workspace Example/PQCheckSDK.xcworkspace -scheme PQCheckSDK -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace Example/PQCheckSDK.xcworkspace -scheme PQCheckThinSDK_Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -workspace Example/PQCheckSDK.xcworkspace -scheme Documentation

after_success:
  - if [ -f ./.travis/publish-docs.sh ]; then
      sh ./.travis/publish-docs.sh;
    fi
